// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBYHWWAEsZRzKxwpuQKfZRUnvZ1YlM6lDI',
    appId: '1:967274712840:web:e831e6936f7482015766bd',
    messagingSenderId: '967274712840',
    projectId: 'flutter-list-exam',
    authDomain: 'flutter-list-exam.firebaseapp.com',
    storageBucket: 'flutter-list-exam.firebasestorage.app',
    measurementId: 'G-G72S4JQS0N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAzFDHeZCxq2tm1TOa6VJdhVFPM5ms7Two',
    appId: '1:967274712840:android:5de8e42239b1b7fb5766bd',
    messagingSenderId: '967274712840',
    projectId: 'flutter-list-exam',
    storageBucket: 'flutter-list-exam.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCrhftWNijP405zZCwtZ53gBpTx0A-6sJQ',
    appId: '1:967274712840:ios:7c6e11e74426ad8b5766bd',
    messagingSenderId: '967274712840',
    projectId: 'flutter-list-exam',
    storageBucket: 'flutter-list-exam.firebasestorage.app',
    iosBundleId: 'com.example.firebaseListExam',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCrhftWNijP405zZCwtZ53gBpTx0A-6sJQ',
    appId: '1:967274712840:ios:7c6e11e74426ad8b5766bd',
    messagingSenderId: '967274712840',
    projectId: 'flutter-list-exam',
    storageBucket: 'flutter-list-exam.firebasestorage.app',
    iosBundleId: 'com.example.firebaseListExam',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBYHWWAEsZRzKxwpuQKfZRUnvZ1YlM6lDI',
    appId: '1:967274712840:web:457df5481b364b275766bd',
    messagingSenderId: '967274712840',
    projectId: 'flutter-list-exam',
    authDomain: 'flutter-list-exam.firebaseapp.com',
    storageBucket: 'flutter-list-exam.firebasestorage.app',
    measurementId: 'G-WW3V8RYJ53',
  );
}
